runtime: java11
instance_class: F1
#manual_scaling:
#  instances: 2
#env_variables:
#  SPRING_PROFILES_ACTIVE: cloud
#  # REPLACE PROJECT_ID with your project ID!
#  MESSAGES_ENDPOINT: https://guestbook-service-dot-PROJECT_ID.appspot.com/guestbookMessages